apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgAz2vh+7ap+KifPlbolmIQw48h3e0lX+ujw8F7FwnQGJS8CxKUS87MsVRJy1iU4K35U93SQl+X5af5hKsESKXglp4TX+Cs+AggMeSNRkyOXcDIKr2lBArPXPgdWk6BSYu7EfXKu1oUy0pofxswDDBLVCwOPvcm2vhv6XZeYewV/FAlonkySt5Sb3pBDvi9JFt+/PSn+Nzlj8NnPSRBWca6S0BLfEAiX1I30bYNSkNkwytFljKu6Jlr6565MbSJ0bqsAIiPVpfpts6c1tjF+T6/Xi0V8Or1CITzTj30x3Y7ategR8fxXMAeliSLFfEOc1Q0g8m8gdc0U7VOIVhMmjCeF50Gb9Wd6GYGLft5Q7SrmoQTH+PabPI5oyTcaqg31yCnZ4XpFokuTNfSvKSTkJCA5HIiPn+g4RbCSwZ7B7KnzgEcBOsIRXp6trRsnJiBiT+u8pI+9d39j4t8YTOE6ZnviFu6Fm1cJbFO99D6rbOSjWFi0Acsl/8UjVIo3fMbEDQT9RTQpZO7KqXashufU3touLznbtHII84FvPXF85ji2laK/+TG3/l0yspdcnRGOJzrDIhNF9UCMgi8glNnP74A4KmokZc9zf87kKLJPS5Ir1/gE5m1p04YeDKPrqGFVukfU9BJp+Qc2ewyWBU4hHOu+25A+ZJDpgsradKevezMiBQhbvp0v/iEDcRUW5GlNVLOEI74NevzJvsnK8xfGSCObzKCSaIlc9ZPzfhuv47CgAityr3IPCmOg
    username: AgAqqKQMf4gTkTz+ZERwz9I+KSIlVqjGuO4sy4ClIh4z8YMoeSv93C0NCrrLRR7CtxgSx1mc5364C8hL71sCr6jfo8r5DL2rjbuM5XOL/xmq2EaJVUHl34Kx/Hp6VSUZJHAqED1mC65AJvqdXkvzna8kUtZdxGg2sOg5i4bAzV2ZZR4y3ToWAVdrn47b8x8TQWtYsmpPrPYMq5DPhaQLDb4VULu0jVhSpIejiplGxq4ql+NXLPP+KMXfBk7NgNnp5JkozR9VkassD1Cpohdy8ahMlUIDBn2lky0D2OhaY8XuOKCpr8JIe92VUKKNiYE/hwx2ObcqppjY7KLe5IijArUFCZFydO++0AJMnZHdQG4ToZeRRfWP9mBpTk+Boup/zarNtAD1iLqdXqMmF94v9QwrXR+ACGWUv6MEyL+/0QRdE8hjh3ehmlJjtAdalFjpwVLFuqL3ZIAJgz8fvzL60WXkGkFg+Sm13aE3h7kOJA2aTUOKnAXIx9CV1txcSEPDWg+nxhFBaiHULBxiF3xoWEX73n0opeNaTSfzHY45bWSQUdV4XLz+w3Mr8F8BGyC8Cc9Scw9BaEe6MU/2flVbE6P1n3Lsr9/Pp1QvbZBK/naqnzAGESkFV71X42dQXeRURY6tqMB+L7la+vvQG3+ujFXHQ9FA99R0QCd5L6sy0IQ+qEuTehwLForkcNvKLA/VU9XagB7UNVk=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
