apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAptIXgITxflMJvA0KafxCaqb5ZxNVi4Ed096xvh2gpXemr+D4mmYjV8azqOzUJXoj9sTFpyLZLSj6ykOGNbx+xbOYCvoK73liT2xP8lt5uiY3T6MjAqkZz0EKns6w6Hz0/u5RKk3SOfatc8iF2mLASum0OBcrU5rHYAxiPjkVk+gIQoyEJpoNONLv3NbwQllbXSmNi7iTkdVGodWjlJWRBi4KJQwa7V4/Wln7Qzt/wYuID/7kwYvsoeRt51sFbV/UpLglrpuZzrM/dm5Y3tzhZSH8J35hVIdJK9akeebZzQiJ4SAY6tOY5i5hmgrTPLf787SMg1NgJ/oLZNKs8SzM9let7nOh9QuR04akfvmZL7SCdMR4MlwLc4nSJvIvMaRTwggmQRLnFKHXwxHa2QhPatKHB9nFrTIFtE6SHOZzWWuYCAqbNwO0kojPgPHVmEfbtJ0SOln62m3VX6dD8AeWPRukIr+ukdWuTH+uESPe1nclb4couRzDkoAs3bSOP6BHylhawBy1A+id+TxdD4YWz4r9OGJMv0u/yPETOq8R6aggpfPqhTX078A7MJ9GLmCtXtwQW+JHOA91BeixpFACfvS5JCbyxAmaYTtYMOzLZwe0aMbHVcL932CJbxw7ta0J2OkEVoik4GSYd8gstO1qtt27pV+y8ejFyOnH2dtrt3ULVJE45Me5GzNrb9zSnWYPeHTcf3FUvtdhjPBLUZ4m9Osg3dg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
