apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCWOCDmd7bpmWNU3zXt4iZsC5e50I/Puv7XsbBoMRpJzEjbpXIFa8iWjTocRXQxA20CUVDoRu9qw1qSpHfAQe6Uw6D4TnEl1GJXin8aEz4O/KzS1elWFQaLoaicIDnzwNYSa0WRtrCVbcPJOABZckrWpgvqd1vC47gk1w5N5SIDjkI98kzzQp3DzKB9JgVlYGkaDDJfEOHs7g1vY7nCatH4fS65Lus463MZ6j3HlmmuFwSPulyz0+yVBYStniPlJBhIt/JEL86N3e2yDZ7M8HzHlbI2FWxPYAdXpDVpAZL/6eQ/Zg3b8kz3o/xuIubwXfc5ylG8u74RBMlmBWfbpNVxi7xpoPQugehSNmRzoR7Jae51ZmEuMGvnP1k2SIoVAaLBFFXQHdgNQ8cAFyTldnimlGjDAUNoC4iOBezC4XmiLT2CgBNLQh5oNElurpLg9NgU1GXqqnVE/agwZBTNZssy6ouYNPfHSKrfIiRwSvKEotTD0bRetg1w+ePd6is/aFc6A8YVir6T90h+BJ7/+7NMhYQALJspFrqER7lNjvI9OtjF2qvyFcvbJejvLE5uvzHGZfO+wq8Y32AmcYSETkceOMoTQ+QM4WCjNG2LznAebe1SD1VXro3NTzRT0QiDNCFrNjtMEcIJYnKbFCEMe0BHaKo9kAh6Zq5A3DCmourwEtbpmpQf7PEwQ2+FwpUxCO1v/ANIzvwpMgUCZ/Zszg5OpAeK+w==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
