apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-stage-bus
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAnOm4ptzLQMgv5/kjF5bEjOpUYSI8JBAUgRUHiCdzj/UlhuTDvVPzHAni+D+1fBYa6xRdUOmuDAicp32YEXTanm4G0Qrk2AfFZRN8do7ejMZSpm2DHOWmWw/LazX26/CDHEN+3Nnvuz9sJDlgaudyyGIdAu5ihQkiLbh+sN9J03p3eT3loknI/FWDuE9A1QDxUXoWpRg7frrTZ+RUl6FPL+kZ2Hgs8pIAAPeTcle99jYack38KaZj37MJoPWyUCtnERx4EW2seg9PA7X34w2MRVyudqIJ0HQICLCKREZzBdH40ZMuvJYaliS3csEiFzvvWhsrqVhsmPel5r4896N6XvJ1mEXAdG+enD+UUoncpgUJIxWHa6ZXOAHws3nPDsNC+rnN9pfLMDC5cB7UmZKO8zPVOjvsNNMFRyOlVoTpHDghFQVHYEXeLou8qRx/BqGaKdj/ythkv4S2WgxqceYZMY2XPEyV5ubVJEtqk/B+8uHSKI0Og5F5HSrE5doYatViiUlOJSDhNQkruZDq0i4JxRp7YE3UwOOR2dtOW9vr44KtNN1UatkwSd7L8mjNCzjGSMJ5xKl/pgL1+ZRPfmw9cgH536KETwgWUzmaCTC+iJAIlYjX0euFPiOHbW6s3V5NcgaDewdZ0+qVHXxdHQ+g68e92jkbhHfZnRaagSpDDRSfVHPfRhIQuzicoLSee29MQ3tFLnqL/hQEfGysgfXLNZ0O5Tw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-stage-bus
      namespace: cicd
    type: Opaque
