apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  creationTimestamp: null
  name: github-push-binding
  namespace: cicd
spec:
  params:
  - name: gitrepositoryurl
    value: $(body.repository.clone_url)
  - name: fullname
    value: $(body.repository.full_name)
  - name: io.openshift.build.commit.ref
    value: $(extensions.ref)
  - name: io.openshift.build.commit.id
    value: $(body.head_commit.id)
  - name: io.openshift.build.commit.date
    value: $(body.head_commit.timestamp)
  - name: io.openshift.build.commit.message
    value: $(body.head_commit.message)
  - name: io.openshift.build.commit.author
    value: $(body.head_commit.author.name)
status: {}
