apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: app-bus
  name: stage-app-bus
  namespace: openshift-gitops
spec:
  destination:
    namespace: stage
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/stage/apps/app-bus/overlays
    repoURL: https://github.com/<your organization>/gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
