apiVersion: v1
kind: Namespace
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/<your organization>/gitops.git?ref=HEAD
  creationTimestamp: null
  name: dev
spec: {}
status: {}
